# Generated by Django 4.2.7 on 2024-03-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productcategory',
            fields=[
                ('prod_cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_brand', models.CharField(max_length=100)),
                ('prod_price', models.IntegerField()),
                ('prod_cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
        ),
    ]
